# Misc Options
splash = false
ipc = true

# DP-3 Wallpaper Block
wallpaper {
    monitor = DP-3
    path = /usr/share/wallpapers/cachyos-wallpapers/Blue.png
    fit_mode = cover
}

# (Optional) Fallback Block for the VIRTUAL monitor
wallpaper {
    monitor =
    path = /usr/share/wallpapers/cachyos-wallpapers/Blue.png
    fit_mode = cover
}

